# Riyam

data <- read.csv("cancer patient data sets.csv")
# We imported the dataset from our working directory.

View(data)

str(data)
# Our dataset has 26 attributes and 1000 observations.
# Also, every attribue of the dataset is an integer, Patient.Id and Level.
# Patient.Id is nominal, Age is numiric, Gender is binary and the rest are ordinal.

is.na(data)
# The dataset has no missing values.

library(dplyr)
samp <- data[, c(2,3,4,9,12, 13, 26)]
mySample <- sample_n(samp, 50)
View(mySample)
# We selected 50 observations from the attributes 2,3,4,9,12,13 and 26 as a sample for our dataset.

#########################

# Ashwag - ?????
hist(data$Smoking)

# The Histogram shows the level frequency of Smoking in patients.
# we noticed that the highest frequency was when the level Alcohol use within this rang [1-3] and [7] and it illustrates there is a lot of outliers in the dataset.

hist(data$Alcohol.use)

# The Histogram shows the level frequency of alcohol use in patients.
# we noticed that the highest frequency was when the level Alcohol use within this rang [1-2] and [7-8]

hist(data$Air.Pollution)

# The Histogram shows the level frequency of Air pollution in patients.
# we noticed that the highest frequency was when the level Air pollution in the 6  and it illustrates there is a lot of outliers  in the dataset.

data$Gender %>% table() %>% pie()
# add percentages
tab <- data$Gender %>% table()
precentages <- tab %>% prop.table() %>% round(3) * 100 
txt <- paste0(names(tab), '\n', precentages, '%') # text on chart
pie(tab, labels=txt) # plot pie chart

# The pie chart shows the Gender of patients.

boxplot(data$Age)

# The age boxplot illustrates there are outlier in age attribute.

plot(data$Dry.Cough, data$Smoking)

# The scatter plot shows that there is no relationship between Dry cough and Smoking.

plot(data$Dust.Allergy, data$Chest.Pain)

# The scatter plot shows that there is no relationship between Dust.Allergy and Chest pain.

plot(data$Air.Pollution, data$Chest.Pain)

# The scatter plot shows that there is no relationship between Air pollution and Chest pain.

boxplot(data$Air.Pollution ~ data$Level)

# The boxplot show there is outliers and Most of the values fall in the medium range and there is no relationship between increasing the level of Air pollution and increasing level of lung cancer.

boxplot(data$Dust.Allergy ~ data$Level)

# The boxplot show there is outliers and Most of the values ​​fall in the medium range and there is no relationship between increasing the level Dust Allergy and increasing level lung cancer.

boxplot(data$Coughing.of.Blood ~ data$Level)

# The boxplot show there is outliers and Most of the values ​​fall in the low range and there is no relationship between increasing the level coughing of blood and increasing level lung cancer.

boxplot(data$Fatigue ~ data$Level)

# The boxplot show there is no outliers and Most of the values ​​fall in the High range and there is a positive relationship between increasing the level fatigue and increasing level lung cancer.

boxplot(data$Shortness.of.Breath ~ data$Level)

# The boxplot show there is outlier and Most of the values ​​fall in the medium range and there is a positive relationship between increasing the level shortness of breath and increasing level lung cancer.

boxplot(data$Wheezing ~ data$Level)

# The boxplot show there is outliers and Most of the values ​​fall in the high range and there is a positive relationship between increasing the level wheezing and increasing level lung cancer.

#########################

## Joud - Data cleaning
## Importing the data set and viewing it
CancerSet = read.csv('cancer.csv')
View(CancerSet)


## Detecting null values, FALSE means no null, TRUE means null
## There is no null values in our data, thus we don't need to replace it with the average value
is.na(CancerSet)
sum(is.na(CancerSet))


## Detecting Outliers
## TRUE represents outlier, FALSE represents non-outlier
library(outliers)

OutAge = outlier(CancerSet$Age, logical = TRUE)
sum(OutAge)
Find_outlier1 = which(OutAge == TRUE, arr.ind = TRUE)
OutAge
Find_outlier1
CancerSet = CancerSet[-Find_outlier1,]

OutAirP = outlier(CancerSet$Air.Pollution, logical = TRUE)
sum(OutAirP)
Find_outlier2 = which(OutAirP == TRUE, arr.ind = TRUE)
OutAirP
Find_outlier2
CancerSet = CancerSet[-Find_outlier2,]

OutAlcohol = outlier(CancerSet$Alcohol.use, logical = TRUE)
sum(OutAlcohol)
Find_outlier3 = which(OutAlcohol == TRUE, arr.ind = TRUE)
OutAlcohol
Find_outlier3
CancerSet = CancerSet[-Find_outlier3,]

OutDust = outlier(CancerSet$Dust.Allergy, logical = TRUE)
sum(OutDust)
Find_outlier4 = which(OutDust == TRUE, arr.ind = TRUE)
OutDust
Find_outlier4
CancerSet = CancerSet[-Find_outlier4,]

OutOccu = outlier(CancerSet$OccuPational.Hazards, logical = TRUE)
sum(OutOccu)
Find_outlier5 = which(OutOccu == TRUE, arr.ind = TRUE)
OutOccu
Find_outlier5
CancerSet = CancerSet[-Find_outlier5,]

OutGenetic = outlier(CancerSet$Genetic.Risk, logical = TRUE)
sum(OutGenetic)
Find_outlier6 = which(OutGenetic == TRUE, arr.ind = TRUE)
OutGenetic
Find_outlier6
CancerSet = CancerSet[-Find_outlier6,]

OutChroncDisease = outlier(CancerSet$chronic.Lung.Disease, logical = TRUE)
sum(OutChroncDisease)
Find_outlier7 = which(OutChroncDisease == TRUE, arr.ind = TRUE)
OutChroncDisease
Find_outlier7
CancerSet = CancerSet[-Find_outlier7,]

OutDiet = outlier(CancerSet$Balanced.Diet, logical = TRUE)
sum(OutDiet)
Find_outlier8 = which(OutDiet == TRUE, arr.ind = TRUE)
OutDiet
Find_outlier8
CancerSet = CancerSet[-Find_outlier8,]

OutObesity = outlier(CancerSet$Obesity, logical = TRUE)
sum(OutObesity)
Find_outlier9 = which(OutObesity == TRUE, arr.ind = TRUE)
OutObesity
Find_outlier9
CancerSet = CancerSet[-Find_outlier9,]

OutSmoking = outlier(CancerSet$Smoking, logical = TRUE)
sum(OutSmoking)
Find_outlier10 = which(OutSmoking == TRUE, arr.ind = TRUE)
OutSmoking
Find_outlier10
CancerSet = CancerSet[-Find_outlier10,]

OutPassiveS= outlier(CancerSet$Passive.Smoker, logical = TRUE)
sum(OutPassiveS)
Find_outlier11 = which(OutPassiveS == TRUE, arr.ind = TRUE)
OutPassiveS
Find_outlier11
CancerSet = CancerSet[-Find_outlier11,]

OutChestPain = outlier(CancerSet$Chest.Pain, logical = TRUE)
sum(OutChestPain)
Find_outlier12 = which(OutChestPain == TRUE, arr.ind = TRUE)
OutChestPain
Find_outlier12
CancerSet = CancerSet[-Find_outlier12,]

OutBloodCoughing = outlier(CancerSet$Coughing.of.Blood, logical = TRUE)
sum(OutBloodCoughing)
Find_outlier13 = which(OutBloodCoughing == TRUE, arr.ind = TRUE)
OutBloodCoughing
Find_outlier13
CancerSet = CancerSet[-Find_outlier13,]

OutFatigue = outlier(CancerSet$Fatigue, logical = TRUE)
sum(OutFatigue)
Find_outlier14 = which(OutFatigue == TRUE, arr.ind = TRUE)
OutFatigue
Find_outlier14
CancerSet = CancerSet[-Find_outlier14,]

OutWeightLoss = outlier(CancerSet$Weight.Loss, logical = TRUE)
sum(OutWeightLoss)
Find_outlier15 = which(OutWeightLoss == TRUE, arr.ind = TRUE)
OutWeightLoss
Find_outlier15
CancerSet = CancerSet[-Find_outlier15,]

OutBreathShortness = outlier(CancerSet$Shortness.of.Breath, logical = TRUE)
sum(OutBreathShortness)
Find_outlier16 = which(OutBreathShortness == TRUE, arr.ind = TRUE)
OutBreathShortness
Find_outlier16
CancerSet = CancerSet[-Find_outlier16,]

OutWheezing = outlier(CancerSet$Wheezing, logical = TRUE)
sum(OutWheezing)
Find_outlier17 = which(OutWheezing == TRUE, arr.ind = TRUE)
OutWheezing
Find_outlier17
CancerSet = CancerSet[-Find_outlier17,]

OutSwallow = outlier(CancerSet$Swallowing.Difficulty, logical = TRUE)
sum(OutSwallow)
Find_outlier18 = which(OutSwallow == TRUE, arr.ind = TRUE)
OutSwallow
Find_outlier18
CancerSet = CancerSet[-Find_outlier18,]

OutClubbing = outlier(CancerSet$Clubbing.of.Finger.Nails, logical = TRUE)
sum(OutClubbing)
Find_outlier19 = which(OutClubbing == TRUE, arr.ind = TRUE)
OutClubbing
Find_outlier19
CancerSet = CancerSet[-Find_outlier19,]

OutCold = outlier(CancerSet$Frequent.Cold, logical = TRUE)
sum(OutCold)
Find_outlier20 = which(OutCold == TRUE, arr.ind = TRUE)
OutCold
Find_outlier20
CancerSet = CancerSet[-Find_outlier20,]

OutDryCough = outlier(CancerSet$Dry.Cough, logical = TRUE)
sum(OutDryCough)
Find_outlier21 = which(OutDryCough == TRUE, arr.ind = TRUE)
OutDryCough
Find_outlier21
CancerSet = CancerSet[-Find_outlier21,]

OutSnoring = outlier(CancerSet$Snoring, logical = TRUE)
sum(OutSnoring)
Find_outlier22 = which(OutSnoring == TRUE, arr.ind = TRUE)
OutSnoring
Find_outlier22
CancerSet = CancerSet[-Find_outlier22,]

## Print the data without outliers
print(CancerSet)


###################
#Riham-statistical measurements 
#calculating the min 1stQu Median mean 3rdQu and the max
summary(mydata$Age)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  14.00   27.75   36.00   37.17   45.00   73.00 
#calculating the variance
var(mydata$Age)
[1] 144.1319
